/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 shoe.gltf --transform
Author: grafi (https://sketchfab.com/zdenkoroman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/puma-shoe-purple-3d-scan-a6d4580e699c4fa1a5967dff3cd4609f
Title: Puma Shoe Purple 3D Scan
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoe-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['default']} position={[0.01, -0.05, 0.05]} rotation={[0, 0, -3.11]} />
    </group>
  )
}

useGLTF.preload('/shoe-transformed.glb')
